backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: assets
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    extension: markdown
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: pages
    label: Strony
    files:
      - name: course_calendar
        label: Terminy
        file: _data/course_calendar.yml
        fields:
          - widget: list
            name: courses
            label: Kursy
            label_singular: Kurs
            fields:
              - name: name
                label: Nazwa
                widget: string
              - name: introductory_class
                label: Spotkanie organizacyjne
                widget: datetime
                time_format: false
              - name: doctor_appointment
                label: Badanie lekarskie
                widget: datetime
                time_format: false
              - name: course_start
                label: Rozpoczęcie szkolenia
                widget: datetime
                time_format: false
      - name: pricing
        label: Ceny
        file: _data/pricing.yml
        fields:
          - name: regular_course
            label: Kurs podstawowy
            widget: number
            value_type: int
            min: 0
            max: 5000
            step: 100
          - name: express_course
            label: Kurs ekspresowy
            widget: number
            value_type: int
            min: 0
            max: 5000
            step: 100
          - name: automatic_transmission_course
            label: Kurs \"automat\"
            widget: number
            value_type: int
            min: 0
            max: 5000
            step: 100
          - name: physical_examination
            label: Badanie lekarskie
            widget: number
            value_type: int
            min: 0
            max: 500
            step: 10
          - name: extra_hour
            label: Dodatkowa godzina
            widget: number
            value_type: int
            min: 0
            max: 500
            step: 10
          - name: extra_hour_bulk
            label: Godziny promocyjne
            widget: number
            value_type: int
            min: 0
            max: 2500
            step: 10
          - name: car_rental
            label: Podstawienie samochodu
            widget: number
            value_type: int
            min: 0
            max: 500
            step: 10
