backend:
  name: git-gateway
  branch: demo # Branch to update (optional; defaults to master)
media_folder: assets/uploads
collections:
  - name: homepage
    label: Strona Główna
    files:
      - name: course_calendar
        label: Terminy
        file: _data/course_calendar.yml
        editor:
          preview: false
        fields:
          - widget: list
            name: courses
            label: Kursy
            label_singular: Kurs
            fields:
              - name: name
                label: Nazwa
                widget: string
              - name: introductory_class
                label: Spotkanie organizacyjne
                widget: datetime
                picker_utc: true
                date_format: "MMMM D, YYYY [(]dddd[)]"
                time_format: "[at] HH:mm"
              - name: doctor_appointment
                label: Badanie lekarskie
                widget: datetime
                picker_utc: true
                date_format: "MMMM D, YYYY [(]dddd[)]"
                time_format: "[at] HH:mm"
              - name: course_start
                label: Rozpoczęcie szkolenia
                widget: datetime
                picker_utc: true
                date_format: "MMMM D, YYYY [(]dddd[)]"
                time_format: "[at] HH:mm"
      - name: pricing
        label: Oferta i Ceny
        file: _data/pricing.yml
        editor:
          preview: false
        fields:
          - widget: string
            name: extra_hour_price
            label: Cena dodatkowej godziny
          - widget: string
            name: extra_hour_bulk_price
            label: Cena promocyjnego pakietu godzin
          - widget: string
            name: physical_examination_price
            label: Cena badania lekarskiego
          - widget: string
            name: car_rental_price
            label: Cena Wypożyczenia Samochodu
          - widget: string
            name: regular_course_price
            label: Cena Kursu Podstawowego
          - widget: list
            name: regular_course_features
            label: Cechy Kursu Podstawowego
            label_singular: Cecha
            fields:
              - widget: string
                name: description
                label: Opis
          - widget: string
            name: express_course_price
            label: Cena Kursu Ekspresowego
          - widget: list
            name: express_course_features
            label: Cechy Kursu Ekspresowego
            label_singular: Cecha
            fields:
              - widget: string
                name: description
                label: Opis
          - widget: string
            name: automatic_transmission_price
            label: "Cena Kursu \"Automat\""
          - widget: list
            name: automatic_transmission_features
            label: "Cechy Kursu \"Automat\""
            label_singular: Cecha
            fields:
              - widget: string
                name: description
                label: Opis
      - name: gallery
        label: Galeria Zdjęć
        file: _data/photo_gallery.yml
        editor:
          preview: false
        fields:
          - widget: list
            name: images
            label: Zdjęcia
            label_singular: Zdjęcie
            fields:
              - name: path
                label: Plik
                widget: image
                allow_multiple: false
                media_library:
                  config:
                    multiple: true
              - name: alt_text
                label: Opis Zdjęcia
                widget: string
      - name: testimonials
        label: Opinie kursantów
        file: _data/testimonials.json
        editor:
          preview: false
        fields:
          - widget: list
            name: testimonials
            label: Opinie
            label_singular: Opinia
            fields:
              - name: clientName
                widget: string
                label: Imię
              - name: product
                widget: string
                label: Wykupiona Usługa
              - name: profilePicture
                widget: image
                label: Portret
                hint: "Zdjęcie o proporcjach 1:1. Wystarczy 48x48 pikseli, ale może być większe. Twarz powinna być w centrum kadru."
              - name: opinion
                widget: markdown
                label: Komentarz
      - name: faq
        label: FAQ - Często Zadawane Pytania
        file: _data/frequently_asked_questions.json
        editor:
          preview: false
        fields:
          - widget: list
            name: questions
            label: Pytania
            label_singular: Pytanie
            fields:
              - name: question
                widget: string
                label: Pytanie
              - name: answer_markdown
                widget: markdown
                label: Odpowiedź
      - name: office-hours
        label: Godziny Otwarcia
        file: _data/office_hours.json
        editor:
          preview: false
        fields:
          - widget: string
            name: monday
            label: Poniedziałek
          - widget: string
            name: tuesday
            label: Wtorek
          - widget: string
            name: wednesday
            label: Środa
          - widget: string
            name: thursday
            label: Czwartek
          - widget: string
            name: friday
            label: Piątek
          - widget: string
            name: saturday
            label: Sobota
          - widget: string
            name: sunday
            label: Niedziela
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    extension: markdown
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
