backend:
  name: git-gateway
  branch: dev # Branch to update (optional; defaults to master)
media_folder: assets/uploads
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    extension: markdown
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: homepage
    label: Strona Główna
    files:
      - name: course_calendar
        label: Terminy
        file: _data/course_calendar.yml
        fields:
          - widget: list
            name: courses
            label: Kursy
            label_singular: Kurs
            editor:
              preview: false
            fields:
              - name: name
                label: Nazwa
                widget: string
              - name: introductory_class
                label: Spotkanie organizacyjne
                widget: datetime
                picker_utc: true
                date_format: "D MMMM YYYY [(]dddd[)]"
                time_format: "HH:mm"
              - name: doctor_appointment
                label: Badanie lekarskie
                widget: datetime
                picker_utc: true
                date_format: "D MMMM YYYY [(]dddd[)]"
                time_format: "HH:mm"
              - name: course_start
                label: Rozpoczęcie szkolenia
                widget: datetime
                picker_utc: true
                date_format: "D MMMM YYYY [(]dddd[)]"
                time_format: "HH:mm"
      - name: pricing
        label: Oferta i Ceny
        file: _data/pricing.yml
        fields:
          - widget: string
            name: extra_hour_price
            label: Cena dodatkowej godziny
          - widget: string
            name: extra_hour_bulk_price
            label: Cena promocyjnego pakietu godzin
          - widget: string
            name: physical_examination_price
            label: Cena badania lekarskiego
          - widget: string
            name: car_rental_price
            label: Cena Wypożyczenia Samochodu
          - widget: string
            name: regular_course_price
            label: Cena Kursu Podstawowego
          - widget: list
            name: regular_course_features
            label: Cechy Kursu Podstawowego
            label_singular: Cecha
            fields:
              - widget: string
                name: description
                label: Opis
          - widget: string
            name: express_course_price
            label: Cena Kursu Ekspresowego
          - widget: list
            name: express_course_features
            label: Cechy Kursu Ekspresowego
            label_singular: Cecha
            fields:
              - widget: string
                name: description
                label: Opis
          - widget: string
            name: automatic_transmission_price
            label: "Cena Kursu \"Automat\""
          - widget: list
            name: automatic_transmission_features
            label: "Cechy Kursu \"Automat\""
            label_singular: Cecha
            fields:
              - widget: string
                name: description
                label: Opis
      - name: gallery
        label: Galeria Zdjęć
        file: _data/photo_gallery.yml
        fields:
          - widget: list
            name: images
            label: Zdjęcia
            label_singular: Zdjęcie
            fields:
              - name: path
                label: Plik
                widget: image
                allow_multiple: false
                media_library:
                  config:
                    multiple: true
              - name: alt_text
                label: Opis Zdjęcia
                widget: string
  - name: pages
    label: Strony
    files:
      - name: pricing
        label: Ceny
        file: _data/pricing.yml
        fields:
          - name: regular_course
            label: Kurs podstawowy
            widget: number
            value_type: int
            min: 0
            max: 5000
            step: 100
          - name: express_course
            label: Kurs ekspresowy
            widget: number
            value_type: int
            min: 0
            max: 5000
            step: 100
          - name: automatic_transmission_course
            label: Kurs \"automat\"
            widget: number
            value_type: int
            min: 0
            max: 5000
            step: 100
          - name: physical_examination
            label: Badanie lekarskie
            widget: number
            value_type: int
            min: 0
            max: 500
            step: 10
          - name: extra_hour
            label: Dodatkowa godzina
            widget: number
            value_type: int
            min: 0
            max: 500
            step: 10
          - name: extra_hour_bulk
            label: Godziny promocyjne
            widget: number
            value_type: int
            min: 0
            max: 2500
            step: 10
          - name: car_rental
            label: Podstawienie samochodu
            widget: number
            value_type: int
            min: 0
            max: 500
            step: 10
      - name: office_hours
        label: Godziny otwarcia
        file: _data/office_hours.json
        fields:
          - name: monday_open
            label: Poniedziałek (otwarcie)
            required: false
          - name: monday_close
            label: Poniedziałek (zamknięcie)
            required: false
          - name: tuesday_open
            label: Wtorek (otwarcie)
            required: false
          - name: tuesday_close
            label: Wtorek (zamknięcie)
            required: false
          - name: wednesday_open
            label: Środa (otwarcie)
            required: false
          - name: wednesday_close
            label: Środa (zamknięcie)
            required: false
          - name: thursday_open
            label: Czwartek (otwarcie)
            required: false
          - name: thursday_close
            label: Czwartek (zamknięcie)
            required: false
          - name: friday_open
            label: Piątek (otwarcie)
            required: false
          - name: friday_close
            label: Piątek (zamknięcie)
            required: false
          - name: saturday_open
            label: Sobota (otwarcie)
            required: false
          - name: saturday_close
            label: Sobota (zamknięcie)
            required: false
          - name: sunday_open
            label: Niedziela (otwarcie)
            required: false
          - name: sunday_close
            label: Niedziela (zamknięcie)
            required: false
